spring.application.name=ProyectoFinal
server.port=96

#formato de los logs
logging.pattern.dateformat=hh:mm

spring.main.banner-mode=off

spring.thymeleaf.cache=false

#Conexión local a la BD Techshop en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_final
 
#Usuario y clave de creaTablas.sql
spring.datasource.username=admin
spring.datasource.password=fitsystem

#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
 
#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

firebase.bucket.name=fitsystem-c876c.firebasestorage.app
firebase.storage.path=fitsystem
firebase.json.path=firebase
firebase.json.file=fitsystem-c876c-firebase-adminsdk-fbsvc-4091d316a3.json

